ALTER TABLE opportunities DROP CONSTRAINT opportunities_stage_check;

ALTER TABLE opportunities ADD COLUMN procedure_date date;

UPDATE opportunities
SET stage = CASE stage
  WHEN 'TO_QUALIFY' THEN 'CONSULTATION_NOT_SCHEDULED'
  WHEN 'EVALUATION_SCHEDULED' THEN 'FOLLOW_UP'
  WHEN 'NEGOTIATION' THEN 'FOLLOW_UP'
  WHEN 'WON' THEN 'CLOSED_WITHOUT_DATE'
  WHEN 'LOST' THEN 'DECLINED'
  ELSE stage
END;

UPDATE opportunities
SET state = 'CANCELLED', reserved_to = NULL, expires_at = NULL
WHERE stage IN ('CONTRACT_PENDING','CLOSED_WITH_DATE','CLOSED_WITHOUT_DATE','DECLINED');

ALTER TABLE opportunities
ADD CONSTRAINT opportunities_stage_check
CHECK (stage IN ('CONSULTATION_NOT_SCHEDULED','FOLLOW_UP','CONTRACT_PENDING','CLOSED_WITH_DATE','CLOSED_WITHOUT_DATE','DECLINED'));

ALTER TABLE opportunities ALTER COLUMN stage SET DEFAULT 'CONSULTATION_NOT_SCHEDULED';

DROP INDEX one_active_opportunity;

CREATE UNIQUE INDEX one_active_opportunity ON opportunities(contact_id)
WHERE stage NOT IN ('CONTRACT_PENDING','CLOSED_WITH_DATE','CLOSED_WITHOUT_DATE','DECLINED');
